#!/usr/bin/env bash

MSG=$(date +'%D')
MSG+=" update"

echo -n "Class Name: "
read class
MSG+=" | ${class}: "
echo -n "Content: "
read content
MSG+=${content}
hold+="x"

echo ""
echo "Press Enter to confirm:"
echo "-------------------------------------------------------"
echo "$MSG"
echo "-------------------------------------------------------"
read -n 1 key

if [[ $key == "" ]]; then
    git pull origin master && \
    git add -A . && \
    git commit -m "$MSG" && \
    git push origin master && \
    echo "Pushed!"
else
    echo "Commit aborted!"
fi
