all: clean install

clean:
	-rm -fr node_modules

install:
	npm install;\
	npm link cluster2;\
	npm link context-config;\
	npm link raptor-config;\
	npm link;

link-pres:
	npm install;\
	npm link raptor;\
	npm link express-raptor;\
	npm link ebay-global-header;\
	npm link ebay-ui-components;\
	npm link raptor-hot-reload;\
	npm link raptor-optimizer-ready-plugin;
